
// NOTE: The following code was generated by "internal/unicode.py", do not edit directly

#pragma once
#include <stddef.h>
#if defined(__cplusplus) && __cplusplus >= 201103L
#include <string_view>
#else
#error "C++11 or later required"
#endif

typedef struct {
    const char* test_name;
    std::u32string_view source;
    std::u32string_view nfc;
    std::u32string_view nfd;
    std::u32string_view nfkc;
    std::u32string_view nfkd;
} NormalizationTest;


extern const NormalizationTest NORMALIZATION_PART_0_TESTS[25];
extern const size_t NORMALIZATION_PART_0_TESTS_SIZE;
extern const NormalizationTest NORMALIZATION_PART_1_TESTS[17029];
extern const size_t NORMALIZATION_PART_1_TESTS_SIZE;
extern const NormalizationTest NORMALIZATION_PART_2_TESTS[1844];
extern const size_t NORMALIZATION_PART_2_TESTS_SIZE;
extern const NormalizationTest NORMALIZATION_PART_3_TESTS[176];
extern const size_t NORMALIZATION_PART_3_TESTS_SIZE;