
// NOTE: The following code was generated by "internal/unicode.py", do not edit directly
//
// Generated from Unicode Version 15.1.0
//
// clang-format off

#pragma once
#include <stdint.h>
#include <stddef.h>
#ifdef __cplusplus
#include <uchar.h>
#define _UCSTEST_C32PTR_T const char32_t * 
#define _UCSTEST_C32_T char32_t
#else
#define _UCSTEST_C32PTR_T const uint32_t *
#define _UCSTEST_C32_T uint32_t
#endif

typedef struct {
    const char * test_name;
    _UCSTEST_C32PTR_T source;
    _UCSTEST_C32PTR_T nfc;
    _UCSTEST_C32PTR_T nfd;
    _UCSTEST_C32PTR_T nfkc;
    _UCSTEST_C32PTR_T nfkd;
} NormalizationTest;

extern const NormalizationTest NORMALIZATION_PART_0_TESTS[25];
extern const size_t NORMALIZATION_PART_0_TESTS_SIZE;
extern const NormalizationTest NORMALIZATION_PART_1_TESTS[17029];
extern const size_t NORMALIZATION_PART_1_TESTS_SIZE;
extern const NormalizationTest NORMALIZATION_PART_2_TESTS[1844];
extern const size_t NORMALIZATION_PART_2_TESTS_SIZE;
extern const NormalizationTest NORMALIZATION_PART_3_TESTS[176];
extern const size_t NORMALIZATION_PART_3_TESTS_SIZE;