
// NOTE: The following code was generated by "internal/unicode.py", do not edit directly

#pragma once
#include <stddef.h>
#ifdef __cplusplus
#include <cuchar>
#define _UCS_TEST_CHAR32_T const char32_t * 
#else
#define _UCS_TEST_CHAR32_T const uint32_t *
#endif

struct NormalizationTest {
    const char * test_name;
    _UCS_TEST_CHAR32_T source;
    _UCS_TEST_CHAR32_T nfc;
    _UCS_TEST_CHAR32_T nfd;
    _UCS_TEST_CHAR32_T nfkc;
    _UCS_TEST_CHAR32_T nfkd;
};

extern const NormalizationTest NORMALIZATION_PART_0_TESTS[25];
extern const size_t NORMALIZATION_PART_0_TESTS_SIZE;
extern const NormalizationTest NORMALIZATION_PART_1_TESTS[17029];
extern const size_t NORMALIZATION_PART_1_TESTS_SIZE;
extern const NormalizationTest NORMALIZATION_PART_2_TESTS[1844];
extern const size_t NORMALIZATION_PART_2_TESTS_SIZE;
extern const NormalizationTest NORMALIZATION_PART_3_TESTS[176];
extern const size_t NORMALIZATION_PART_3_TESTS_SIZE;